name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android Build Tools & Aidl
      run: |
        sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-dev autoconf automake libtool pkg-config cmake zlib1g-dev
        pip install --upgrade pip
        pip install buildozer cython virtualenv openpyxl

    - name: Build with Buildozer
      run: |
        # Sunucunun ve az önce kurduğumuz resmi SDK yollarını Buildozer'a dikte ediyoruz
        export ANDROID_HOME=$ANDROID_HOME
        export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0
        
        # Buildozer'ı ateşle
        buildozer -v android debug --auto-accept-sdk-license
